server:
  port: 8080
spring:
  datasource:
    username: root
    password: znzedushangzhe
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml




