#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://duckflew.cn:3306/hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=znzedushangzhe
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jackson.serialization.indent_output=true
#
## JWT Config
#jwt.header=Authorization
#jwt.secret=NDU0NTY4amhmc3NkeHp6eGNxdzIlMjFAJTIxQCUyM2ZmNQ==
##120分钟
#jwt.expiration=7200000
#
#spring.redis.port=6379
#spring.redis.host= duckflew.cn
#spring.redis.database= 0
#spring.redis.password= znzedushangzhe
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0

server:
  # 端口
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://duckflew.cn:3306/hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: znzedushangzhe

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: duckflew.cn
    port: 5672
    username: duckflew
    password: duckflew
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1297087462@qq.com
    password:  jpbuogawvozqbaed
    #    ludqpqieltkhicei
    properties:
      mail.debug: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    port: 465
  redis:
    port: 6379
    host: duckflew.cn
    database: 0
    password: znzedushangzhe
    pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

inviteMail:
  title: 邀请
  content: 邀请您加入  点击如下链接同意