server:
  port: 8080
spring:
  datasource:
    username: root
    password: znzedushangzhe
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://duckflew.cn:3306/testdb?serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: Mapper/*.xml
logging:
  level:
    cn.duckflew: info
  file:
    path: ./springboot-mybatis/log


