spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: znzedushangzhe
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
#    校验流程文件 默认检测Resources文件夹下的Process文件夹里面的流程定义
    check-process-definitions: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

