server:
  port: 8080
spring:
  datasource:
    username: root
    password: znzedushangzhe
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  redis:
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    host: 127.0.0.1
    lettuce:
      shutdown-timeout: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



